@echo off
del /q any_python.txt
del /q registry_output.txt
del /q program_files.txt
del /q program_files_utf8.txt
del /q program_files_x86.txt
del /q program_files_x86_utf8.txt
del /q processes.txt
del /q python_processes.txt
del /q kill_log.txt
del /q kill_log_2.txt
del /q find_python.ps1
del /q find_python_pure.ps1
del /q find_any_python.ps1
del /q check_processes.ps1
del /q check_processes_file.ps1
del /q check_registry.ps1
del /q list_programs.ps1
del /q list_programs_utf8.ps1
del /q get_python_processes.ps1
del /q test_status.ps1
