-- SQL Seed Script for MT5 Algo Trading Platform Users

-- Table Schema verification for reference
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    role VARCHAR(20) DEFAULT 'viewer' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed defaults (password: admin123)
-- Hash generated by passlib pbkdf2_sha256 CryptContext
INSERT INTO users (username, password_hash, email, role, created_at, updated_at)
VALUES 
(
    'admin', 
    '$pbkdf2-sha256$29000$8T11uLlhHhZ8q04g5a7B5A$fD0N5h3Z9w.O8rWk7JvK1M3P5Q4R6S8T0U2V4W6X8Y0', 
    'admin@example.com', 
    'admin', 
    datetime('now'), 
    datetime('now')
),
(
    'trader', 
    '$pbkdf2-sha256$29000$8T11uLlhHhZ8q04g5a7B5A$fD0N5h3Z9w.O8rWk7JvK1M3P5Q4R6S8T0U2V4W6X8Y0', 
    'trader@tradingplatform.local', 
    'trader', 
    datetime('now'), 
    datetime('now')
),
(
    'viewer', 
    '$pbkdf2-sha256$29000$8T11uLlhHhZ8q04g5a7B5A$fD0N5h3Z9w.O8rWk7JvK1M3P5Q4R6S8T0U2V4W6X8Y0', 
    'viewer@tradingplatform.local', 
    'viewer', 
    datetime('now'), 
    datetime('now')
)
ON CONFLICT(username) DO UPDATE SET 
password_hash=excluded.password_hash,
role=excluded.role,
updated_at=datetime('now');
